version: "3.8"
services:
  dev_core:
    build:
      context: docker/ros
      args:
        - user_id=1000
        - ros_ws=/home/developer/catkin_ws

    network_mode: host

    # Enabling GPU access with Compose
    # https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
             - capabilities: [gpu]
               count: all

    environment:
      - TERM=xterm-256color
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER

    volumes:
      - ./data:/home/developer/data 
      - ./dev_ws:/home/developer/catkin_ws
      - ./docker/ros/.ros:/home/developer/.ros
      - ./docker/ros/.gazebo/:/home/developer/.gazebo
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
